words = [
    "CLI",
    "biome",
    "codeglue",
    "culori",
    "drackett",
    "esac",
    "luxon",
    "mcp",
    "monorepo",
    "paradigm",
    "submodule",
    "suppressions",
    "tailnet",
    "tiltshift",
    "tsconfig",
    "vitest",
    "volta",
]
ignore_paths = ["yarn.lock"]
